name: cd

on:
  push:
    branches: [main]

jobs:
  setup-gcloud:
    name: Setup GCloud
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 363.0.0"

      - name: Build and Upload the Image
        run: gcloud builds submit --tag europe-southwest1-docker.pkg.dev/notely-414806/notely-ar-repo/notely:latest ./Dockerfile

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run Build Script
        run: ./scripts/buildprod.sh
