name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run Build Script
        run: ./scripts/buildprod.sh

      - name: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 363.0.0"

      - name: Build and Upload the Image
        run: gcloud builds submit --tag europe-southwest1-docker.pkg.dev/notely-414806/notely-ar-repo/notely:latest .

      - name: Run migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-southwest1-docker.pkg.dev/notely-414806/notely-ar-repo/notely:latest --region europe-southwest1 --allow-unauthenticated --project notely-414806 --max-instances=4
